version: '3.8'

services:
  mongo-auth:
    image: mongo:4.4
    container_name: mongo-auth
    networks:
      - ecom-network

  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      MONGODB_URI: mongodb://mongo-auth:27017/authdb
      JWT_SECRET: token
    depends_on:
      - mongo-auth
    networks:
      - ecom-network
  mongo-product:
    image: mongo:4.4
    container_name: mongo-product
    networks:
      - ecom-network
  
  product-service:
    build: ./services/product-service
    container_name: product-service
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo-product:27017/productdb
    depends_on:
      - mongo-product
    networks:
      - ecom-network
    
networks:
  ecom-network:
      